### ISSUE TITLE
Format output js for the data files

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#104]

**Comment by fershad** [comment]
To make it easier to read and share the marginal/average intensity data, we should provide a formatted version of the JS and JSON files generated as part of #102 and #100.

A minified version should also be retained to facilitate importing the data into CO2.js at a later time.

**Comment by fershad** [comment]
This can be done with Prettier. Leaving this gist as a reference https://gist.github.com/Mohamed3on/840b34ecb7e9abf06ace035183b7f1fc
