### ISSUE TITLE
Please include the dist files

### ISSUE THREAD

**Issue by inod** [thegreenwebfoundation/co2.js#105]
Downloading and installing npm, all the toolchain required and dependencies, and then building the dist files is wasteful, if all I want to do is to start experimenting with the dist/iife file you mention in README.md.

Is there a technical reason you don't include the dist directory?

**Comment by fershad** [comment]
@inod good point, thanks from bringing this up. I don't see any reason why the `/dist` directory cannot be committed to git as well. As you say, having those files available would let folks start using CO2.js without NPM at all.

Let's just check with @mrchrisadams if there's any reason why `/dist` was excluded from git originally.

**Comment by mrchrisadams** [comment]
hey folks, I can't remember specifically, but these are two reasons I can remember:

1. it seemed a bit redundant to check-in generated and minified code, when CDNs already host the files for playing around with already. I've linked to some examples below
2. Previously, I've tried to keep generated code out of projects if I can - I've found it would result in smaller and slightly easier to read commits and PRs to review. I'm not typically reading the code in `dist` - it's aimed at machines, and it would be easy for me to end up checking in minified, or transpiled code without knowing if it _really_ was the same as the code in `src`, so not including the `dist` file seemed a way to avoid this error.

**An example of fetching code without needing NPM**

Jsdeliver is one example service that takes files from npm, and hosts them so you can refer to them in scripts in your own code without needing to use NPM directly yourself. It's also served from a CDN already.

Here's the link to the package:

https://www.jsdelivr.com/package/npm/@tgwf/co2

You can follow the links there to the (minifed) IIFE file for linking:

https://cdn.jsdelivr.net/npm/@tgwf/co2@0.10.4/dist/iife/index.js

Another one is [unpkg](https://unpkg.com/). You can see the same release below:

https://unpkg.com/browse/@tgwf/co2@0.10.4/

And here's the 
https://unpkg.com/@tgwf/co2@0.10.4/dist/iife/index.js

Does this help meet the use case listed above? It would be trivial to add this to the docs, to make it easier to start without needing to mess with npm.

**On checking generated code into git**

This isn't a strongly help opinion. If there are libraries that do this regularly, and they have a way we can copy to get code checked in a safe way that avoids common errors, and addresses the issues above it it woudl be a nice thing for hacktobefest :)

**Comment by fershad** [comment]
Thanks @mrchrisadams. As you mention, the output in `dist` is for machines, and it would be hard to us to verify that it's been updated correctly before merging a PR as well.

@inod do the unpkg and/or jsdelivr suggestions work for you? I can put these into the docs & readme over the weekend.

**Comment by inod** [comment]
Thank you very much @fershad and @mrchrisadams, I was able to use the linked built js from jsdelivr successfully.

**Comment by fershad** [comment]
Added to the readme in 170400d, and updated on the docs site too in https://github.com/thegreenwebfoundation/developer-docs/commit/3bcf89d4ec0321acc83e18a7718e2c6877a9d7e3.
