### ISSUE TITLE
Functions  in co2

### ISSUE THREAD

**Issue by soulgalore** [thegreenwebfoundation/co2.js#11]
Hi @mrchrisadams so I haven't checked before but the [co2 file](https://github.com/thegreenwebfoundation/co2.js/blob/master/src/co2.js) include a lot of sitespeed.io or at least pagexray functionality. I'm, thinking do you really want that? For other implementers the key function is getting the co2 per byte.

**Comment by mrchrisadams** [comment]
I was thinking about this too - I think the xray page representation is really helpful, and would be useful for a bunch of other tools I'm working on, like [greentrace](github.com/thegreenwebfoundation/greenhouse/).

Specifically, I was thinking of using pagexray to act as a useful tool for taking har files, and building traceroute maps for every domain listed in a pagexray object, showing the 'green' vs 'grey' hops. 

That said, given that the domains key in a page object isn't too complex, I think I'd be a bit happier with a separate module for this eventually, like `page.js` or something.

So all the co2 file would ideally do would be provide sensible emissions factors for the data sent over the wire, accounting for the location and kind of energy being used.

Given how few people use co2.js now though, I think I'm able to make a PR for sitespeed if I end up extracting this out.

**Comment by soulgalore** [comment]
Ok, lets close this for now and then we can update docs in coming PRs.
