### ISSUE TITLE
Updated 'users of CO2.js' in our docs

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#114]
We know more folks are using CO2.js in their  own software. 

It would be great to list them in the repo or the docs

**Comment by fershad** [comment]
Realised that I also have a similar issue open in the docs repo.
https://github.com/thegreenwebfoundation/developer-docs/issues/8

**Comment by mrchrisadams** [comment]
Good point. Let's close this one and and use that as the canonical one we refer to. We can always update this every few months if need be.
