### ISSUE TITLE
Is there a way we can allow carbon intensity value to be passed into swd calculations? Also seems like the green web hosting check is not being used at all in SWD model

### ISSUE THREAD

**Issue by mohan-murali** [thegreenwebfoundation/co2.js#132]
Hi,

Is there a way in which I can pass a carbon intensity value into the perVisit and perByte function to help me in calculating the co2? Also it seems that current the green web hosting flag is not being used at all. I feel that it is wrong.

![image](https://user-images.githubusercontent.com/26025710/220338028-606739e9-6dbc-4cba-973c-092c75151863.png)

**Comment by fershad** [comment]
In the v0.12.0 release we introduced two new functions which allow for custom CO2 intensity figures to be passed into the SWD model. We're working on documenting this on the developer docs site, but these release notes should help you get started.

https://www.thegreenwebfoundation.org/news/release-guide-co2-js-v0-12/

@mohan-murali could you elaborate on what you mean by the green web hosting flag not being used at all?

**Comment by mohan-murali** [comment]
Thanks, I will check that.
 In the below method in co2.js we are passing the green flag.

**Comment by mohan-murali** [comment]
<img width="817" alt="Screenshot 2023-02-21 at 12 48 10" src="https://user-images.githubusercontent.com/26025710/220349334-37965516-d401-4101-8134-22d8e2a63e93.png">

**Comment by mohan-murali** [comment]
Sorry, Just now checked the code. Seems like it is being used. Closing the issue. Thanks for the help!
