### ISSUE TITLE
Can we have different metrics for different file types?

### ISSUE THREAD

**Issue by mgifford** [thegreenwebfoundation/co2.js#139]
I think we all would assume that a 1mb jpg on an average HTML site would consume less energy than a 1mb JavaScript file. I do think this is a reasonable assumption. 

Yet right now I don't think that CO.js is factoring that in. 

I don't know what the multiplier should be for the JS, but that is something that we could test out with profilers and then adjust over time. 

Does this seem like a reasonable addition?

**Comment by fershad** [comment]
@mgifford I've probably explained why CO2.js doesn't do this at the moment in my reply to #138. Pasting below as well for anyone stumbling upon this issue.

> When it comes to generating carbon estimates, CO2.js is simply a wrapper around existing accepted models. That is to say, there's no "secret sauce" in CO2.js or no additional functionality that CO2.js adds around these models. That is to say, if a model used data transfer, time on site, and CPU usage as the input for calculating carbon emissions, then that's what CO2.js will have the input. Currently, there's no such model - or at least no such model implemented in CO2.js.

**Comment by mgifford** [comment]
Let's close this for now. I think we can focus on discussing this in #138
