### ISSUE TITLE
Automate fetching of new average annual grid intensity data

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/co2.js#143]
Currently, it is a manual process to update average grid intensity data from Ember. Now that #125 has been deployed, and we're using the Ember API to fetch data we can look to automate this process.

**Comment by tackaberry** [comment]
hey @fershad and @mrchrisadams.  I have one more for you.  I have an idea for this one too. 

I wrote a github action that will run on a schedule and manual to automatically create a PR for updated data.  Then you manually mege the PR. 

Check this out:
https://github.com/tackaberry/co2.js/pull/2

If this is the kind of automation you're looking for, I can make a PR for the workflow.

**Comment by mrchrisadams** [comment]
Thanks for this @tackaberry - I've assigned it to Fershad as he's a bit more familiar with that part of the codebase than I am.

**Comment by fershad** [comment]
Thanks @tackaberry I'll check this out later in the week.

**Comment by fershad** [comment]
@tackaberry this look good to me. Can you create a PR for this please.

I've got some comments around timing & wording, but I can make those changes in the PR itself :)
