### ISSUE TITLE
Release 0.13.3 not working / breaking changes

### ISSUE THREAD

**Issue by Manuel-Steinberg** [thegreenwebfoundation/co2.js#146]
## Error
```js
Uncaught TypeError: Cannot read properties of undefined (reading 'data')
at index.js:18:48
at index.js:7:68
```
Which points me to here...

```js
// These carbon intensity figures https://ember-climate.org/data/data-explorer
// - Global carbon intensity for 2022
const GLOBAL_GRID_INTENSITY = averageIntensity.data["WORLD"];❌
```

That looks like this merge a couple of days ago:  #142 

----

Which leads to an error in my JS
```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'co2')
```

## Reproduce

HTML code:

```html
<script defer type="text/javascript" src="https://unpkg.com/@tgwf/co2@0.13.3/dist/iife/index.js"></script>
```

JS code:

```js
const emissions = new co2.co2({model: "swd"});

const bytesSent = webAnalyse.bytes // value is set
const greenHost = webAnalyse.green // value is set
let estimatedCO2 = emissions.perVisit(bytesSent, greenHost).toFixed(3) 
```

## Solution (Work-around)

Switching back to the previous version inside the HTML fixed the issue.
```html
<script defer type="text/javascript" src="https://unpkg.com/@tgwf/co2@0.13.2/dist/iife/index.js"></script>
```

**Comment by fershad** [comment]
@Manuel-Steinberg sorry that you've encountered this. I have released a patch version which solves for this in my testing.

**v0.13.3**
https://gitpod.io/#https://github.com/thegreenwebfoundation/co2.js/tree/v0.13.3

**v0.13.4**
https://gitpod.io/#https://github.com/thegreenwebfoundation/co2.js/tree/v0.13.4

Run `npm install` and then `npm run gitpod` to test it in the browser.

This wasn't picked up by our test suite, as we don't have coverage for running tests on the IIFE version in the browser. I'll have a think about how/if we can solve for that.

**Comment by Manuel-Steinberg** [comment]
Don't be sorry @fershad 😉

I admit that I'm not a big fan / user of npm and "modern" JS. I do not really know the difference between CommonJS, ES Modules, etc. ... 

The reason why I am using the IIEF version is that I could add it via script tag and let's go 😬 quick and easy or call it "old-school" 🤓 But it was working! So I just hope this option will not disappear in future releases 😅

**Comment by fershad** [comment]
No plans on it disappearing soon :)
