### ISSUE TITLE
Update changelog.md to include recent releases

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#154]
Our last few releases  of CO2.js currently are not reflected in CHANGELOG.md.

It's fairly a reasonable place for developers to look for a summary of changes, and the file also says that all notable changes wil be documented there:

> All notable changes to this project will be documented in this file.
>
> The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
>
> - **Added** for new features.
> - **Changed** for changes in existing functionality.
> - **Deprecated** for soon-to-be removed features.
> - **Removed** for now removed features.
> - **Fixed** for any bug fixes.
> - **Security** in case of vulnerabilities.

We have a series of blog posts the the library which outline the key changes in the last few point releases, like 0.11, 0.12, and 0.13:

https://www.thegreenwebfoundation.org/tags/release-notes/

Including these according to the format outlined in changelog.md would be nice quality of life improvement, especially with our recent move to monthly updates of carbon intensity in the data introduced by [#152](https://github.com/thegreenwebfoundation/co2.js/pull/152) - I can see people scratching their head over why their numbers are slightly different from version to version if we do not clearly signpost these changes.

**Comment by fershad** [comment]
I've updated the changelog until the latest release.
https://github.com/thegreenwebfoundation/co2.js/commit/214d11c16f684368adb17ae14e5a716c5a7c1542
