### ISSUE TITLE
Make contributors more visible

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/co2.js#159]
It would be great to give more visibility to the contributor who have helped get CO2.js to where it is today & who continue to push for its development.

This can be done using the [All Contributors](https://allcontributors.org/en) specification. There is an associated Github bot that makes for an easier integration with this platform.

Key instructions are below:
[Installing the Bot](https://allcontributors.org/docs/en/bot/installation)
[Using the Bot](https://allcontributors.org/docs/en/bot/usage)
[Configuring the Bot](https://allcontributors.org/docs/en/bot/configuration)

**Comment by fershad** [comment]
@mrchrisadams can you please help activate the @ allcontributors bot for this repo. It requires organisation admin permissions on Github.

Instructions on how to do so are here: 
https://allcontributors.org/docs/en/bot/installation

Once that is done, please ping me & I'll take care of the rest :)

**Comment by fershad** [comment]
Strange. I'm still not seeing it come up as a @ option in comments. Nothing urgent, can work this out next week.

**Comment by hanopcan** [comment]
Hey @fershad I just double-checked this and is does look enabled to me.

The next step it recommends is to update the readme file. Let me know if there's anything I can do to help unblock this

**Comment by fershad** [comment]
Interesting @hanopcan maybe I don't have the right organisation privileges (??).

I updated the readme already in ae078e5 but when I tried to prompt the bot to do it's thing it came with a "no can do". https://github.com/thegreenwebfoundation/co2.js/pull/1#issuecomment-1659932552

One we can talk through later today.

**Comment by fershad** [comment]
I finally got this working by using the CLI instead. I've created #165 to create a proper `CONTRIBUTING.md` file which introduces people with how to get involved with this project & add themselves as a contributor on future commits.
