### ISSUE TITLE
Update function comments

### ISSUE THREAD

**Issue by drydenwilliams** [thegreenwebfoundation/co2.js#164]
**Describe the bug**
The `params` in comments doesn't match the code arguments

**To Reproduce**
1. Go to [#L162](https://github.com/thegreenwebfoundation/co2.js/blob/main/src/sustainable-web-design.js#L162) and view param, it expects be a `number`
2. Go to [#L173](https://github.com/thegreenwebfoundation/co2.js/blob/main/src/sustainable-web-design.js#L173) which throws an error if it's not a `boolean` 

**Expected behavior**
Ideally, it would accept a `number` for `carbon intensity` not a `boolean` what does this toggle, if it's "green" or not?

**Comment by fershad** [comment]
I know there's a reason the code ([#L173](https://github.com/thegreenwebfoundation/co2.js/blob/main/src/sustainable-web-design.js#L173)) is like that, but I'll need to dig into the memory bank as to why.

Regardless, yes the JS Doc comments do need to be updated to reflect what types are accepted.

**Comment by fershad** [comment]
@drydenwilliams yeah the comments were showing the incorrect type. `number` should have been `boolean`. I've fixed that in #167.
