### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/co2.js#165]
Create a `CONTRIBUTING.md` to outline how folks can get involved with this project & how to add themselves as a contributor.

**Comment by fershad** [comment]
Organisation wide contributing and code of conduct files have been created in https://github.com/thegreenwebfoundation/.github

**Comment by mrchrisadams** [comment]
Awesome work Fish - I've just seen the funding, code of conduct and other links show up on a bunch of our projects from the changes you made 💚
