### ISSUE TITLE
thegreenwebfoundation.org down???

### ISSUE THREAD

**Issue by nieebel** [thegreenwebfoundation/co2.js#169]
I cannot access https://thegreenwebfoundation.org/ ❌
While https://admin.thegreenwebfoundation.org/ works ✅

**Comment by mrchrisadams** [comment]
hi @Niebel! Thanks for reporting this.

There was a bout 10 mins of downtime on the API yesterday around 2pm, which would have meant that  https://admin.thegreenwebfoundation.org would have been unreachable.

Can you confirm that it was the site below that was down?
https://www.thegreenwebfoundation.org/

**Comment by fershad** [comment]
Going to close this since it's not something to work on as part of this repo.
