### ISSUE TITLE
Quick start not found

### ISSUE THREAD

**Issue by bortzmeyer** [thegreenwebfoundation/co2.js#172]
On https://www.thegreenwebfoundation.org/co2-js/, clicking "Quick start guide" yields 404 "It seems we can’t find what you’re looking for. Perhaps searching can help.".

**Comment by mrchrisadams** [comment]
Hi @bortzmeyer sorry about that. This is the intended page - we must have missed it when moving a page.

https://www.thegreenwebfoundation.org/news/start-calculating-digital-carbon-emissions-in-5-minutes-with-co2-js/

I've set up a redirect now, so following the link should work.
