### ISSUE TITLE
perVisitTrace options doesn't support 0 percentages

### ISSUE THREAD

**Issue by p-gerard** [thegreenwebfoundation/co2.js#173]
**Describe the bug**

When using `0` as a percentage with the `perVisitTrace` methods, the actual used value is `0.25`

**To Reproduce**

Run the following code snippet
```js
const { co2 } = require('@tgwf/co2');

const co2Swd = new co2({ model: 'swd' });

const result = co2Swd.perVisitTrace(100, false, {
  dataReloadRatio: 1,
  firstVisitPercentage: 1,
  returnVisitPercentage: 0,
});

console.log(result);
```

**Expected behavior**

The returnVisitPercentage used should be `0`, but it is instead `0.25`

```js
{
  co2: 0.000044272575,
  green: false,
  variables: {
    // ...
    returnVisitPercentage: 0.25 // <-
  }
}
```

**Environment:**
 - NodeJS
 - Browser

**Additional context**

This seems to be caused by the `||` operator to set default values
Replacing it with `??` should fix the issue, see:
https://github.com/thegreenwebfoundation/co2.js/blob/4eea072fd7879469231cf1d4c1284ce4c9d4225f/src/co2.js#L178-L180

**Comment by fershad** [comment]
@p-gerard thanks for this pick up.

I won't be able to give this attention until the weekend. If you've got the capacity, you can go ahead and create a PR with a fix too~

**Comment by fershad** [comment]
Reopening this issue. It there is still a problem with 0 values not flowing through to the results. For example:

```
const options = {
  dataReloadRatio: 0,
  firstVisitPercentage: 0,
  returnVisitPercentage: 0,
  gridIntensity: {
    device: 0,
    dataCenter: 0,
    network: 0,
  },
}

const estimatedCO2 = co2Emission.perVisitTrace(1000000, false, options);
```

Returns:

```
{
  "co2": 0.26740635300000004,
  "green": false,
  "variables": {
    "description": "Below are the variables used to calculate this CO2 estimate.",
    "bytes": 1000000,
    "gridIntensity": {
      "description": "The grid intensity (grams per kilowatt-hour) used to calculate this CO2 estimate.",
      "network": 0,
      "dataCenter": 0,
      "production": 437.26,
      "device": 0
    },
    "dataReloadRatio": 0,
    "firstVisitPercentage": 0,
    "returnVisitPercentage": 0
  }
}
```

The total CO2 value should actually be 0, since there's no first time users & no repeat users.
