### ISSUE TITLE
Add source headers to hosting API calls

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/co2.js#181]
**Is your feature request related to a problem? Please describe.**
Not a problem, but something that help us (Green Web Foundation) later down the line to understand where API requests are coming from.

**Describe the solution you'd like**
Add a custom header `x-greencheck-src` to the API fetch requests made to the Greencheck API.

https://github.com/thegreenwebfoundation/co2.js/blob/51b85e23dc1f52ac6642259c09e56fef62948087/src/hosting-api.js#L23-L25

https://github.com/thegreenwebfoundation/co2.js/blob/51b85e23dc1f52ac6642259c09e56fef62948087/src/hosting-api.js#L41

There should be a default value `x-greencheck-src: "co2js"` but there should be a mechanism for that to be changed to a value that's set by the user.

**Comment by mrchrisadams** [comment]
Fish, given the traffic we get I'm very much in favour of this, but would you mind adding a bit of info outlining the where the `x-greencheck-src: "co2js` syntax came from? I get the `x-` prefix for unnofficial headers, but the rest I'm less confident commenting because I'm not so familiar with comparable prior work.
 
I think there may be existing conventions we can refer to for identifying API clients or user agents, that have been implemented in various tooling for parsing logs, rate-limiting and so on.

This would save us work further down the line if we follow an existing convention or spec for handling API traffic.

**Comment by fershad** [comment]
Maybe @philsturgeon might have some idea.

Phil, we're hoping to introduce a way to see how many checks against the Green Web Dataset API are coming from different tools/providers.

I've suggested the idea of a custom `x-` header here as a way for folks to self-report when sending a request. Outside of an API key solution, is there any other convention for how might be able to do this?

**Comment by philsturgeon** [comment]
From what I'm understanding of the requirements you can use the User Agent header for this. That's exactly what its for!

**Comment by philsturgeon** [comment]
Anyone and everyone can set the user agent header, most just don’t bother. I generally get iOS clients to set it so I can see which versions people are using without invasive telemetry, things like that, so this seems like basically the same thing.

**Comment by sfishel18** [comment]
👋 hello! i came across this project in the Frontend Focus newsletter, and if you're looking for new contributors i'd love to help out! this particular issue looks like a good introductory one. could i take a crack at it?

**Comment by fershad** [comment]
@sfishel18 thanks for reaching out. We'd love a PR for this. Based on the conversation between Chris and Phil above, here's a small spec:

- Add a `User-Agent` header to the fetch requests in the original comment.
- The header should have the value `co2js/<version>`, where `<version>` is the version number of the library being used to make the request.
- Ideally, the version number should update by itself, without us having to manually change it every release.

Let me know if you get stuck or need a hand.
