### ISSUE TITLE
Document different ways to calculate per domain calculations and how this changes figures

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#183]
This is a follow on issue from  #182, where removing page Xray specific functions means we non longer have an implicit 'recommended' way to tally up emissions per domain.

This may be a decision you delegate to specific models like how SWD has specific implementations of a public methods, like `perbyteTrace()`:

https://developers.thegreenwebfoundation.org/co2js/methods/#perbytetrace-sustainable-web-design-only

Either way, being more explicit at least would help make it clearer why some values are different to others across calculators when using the same code.

**Comment by fershad** [comment]
@mrchrisadams this should be a pretty easy write up for the docs, although I'm not sure off the top of my head what section of the site it would live in.

Will aim to get around to this late January/early Feb.

**Comment by fershad** [comment]
I've removed this as a milestone for 0.15 as it shouldn't tie to a release.

@mrchrisadams I've created a card in our internal Trello board to track this, as I think it would be good as a technical post on our blog. Okay to close this & track progress in Trello instead?

**Comment by mrchrisadams** [comment]
Hey @fershad - works for me. thanks for letting me know.
