### ISSUE TITLE
Look into the use of JSR as a distribution channel for co2.js

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#194]
JSR is another package repository announced by the folks working on Deno that is interesting, and seems to offer some material benefits over using npm. You can see more below:

https://jsr.io/#why-jsr

One big thing is cross platform support:

> The goal of JSR is to work everywhere JavaScript works, and to provide a runtime-agnostic registry for JavaScript and TypeScript code. Today, JSR works with Deno and other npm environments that populate a node_modules. This means that Node, Bun, Cloudflare Workers, and other projects that manage dependencies with a package.json can interoperate with JSR as well.
>
> We intend to expand our support of bundlers and other runtimes as time goes on, and document the APIs and techniques for doing so.

There's a few other things in its favour that might interest us:

> JSR is intended to be secure, fast, and flexible, and also work well in resource-constrained environments.
> JSR uses a global CDN to serve packages, and uses local caching and high parallelism to speed up downloads.
> JSR package uploads are immutable, so you can trust that packages will never change after downloading them or disappear underneath you.
> JSR package downloads are efficient, downloading only the exact files you are importing.

This isn't a priority right now, but it might be worth taking a look at how complicated it would be support it, and what the tradeoffs are compared to using npm-only.

The [announcement blog post is worth a look too](https://deno.com/blog/jsr_open_beta).

**Comment by fershad** [comment]
@mrchrisadams I think we can do this pretty easily, at least to reserve the `@tgwf` scope and `co2` package name.

I've created the scope & sent you an invite.

**Comment by fershad** [comment]
@mrchrisadams I've also created an `@greenweb` scope which we can use going forwards.

I will look to publish CO2.js v0.16 to JSR in the next few weeks as a test. This will only be a test to see how the process works, and explore the kind of project documentation JSR is able to produce. I will not update any of our existing docs/readme to point to installing from JSR at this time.

**Comment by fershad** [comment]
This has been addressed in the v0.16 release notes.
https://www.thegreenwebfoundation.org/news/release-guide-co2-js-v0-16/#jsr
