### ISSUE TITLE
Typos in contributors file

### ISSUE THREAD

**Issue by hanopcan** [thegreenwebfoundation/co2.js#214]
**Describe the bug**
Only a minor thing - there are a few typos in the contributors.md file.

**To Reproduce**
1. Go to https://github.com/thegreenwebfoundation/co2.js/blob/main/CONTRIBUTING.md
2. Have a read, you'll spot a few minor typos.

**Expected behavior**
No typos!

**Environment (please complete the following information):**
n/a

**Additional context (if applicable)**
n/a

**Comment by fershad** [comment]
Thanks @hanopcan. I've merged the changes you've made, and will touch up the titles of the issue templates so that they align with what's in contributing guidelines.
