### ISSUE TITLE
Add JSDoc comments to grid intensity data files and generation script files

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/co2.js#229]
To help folks coming to the library better understand the average and marginal grid intensity data that is currently available in CO2.js, there should at least be JSDoc comments for both the [script files that update the data](https://github.com/thegreenwebfoundation/co2.js/tree/main/data/functions), as well as the [generated data files](https://github.com/thegreenwebfoundation/co2.js/tree/main/src/data) that are in the src folder.

**Comment by Malay-dev** [comment]
Hey, can I work on this issue?

**Comment by fershad** [comment]
Hi @Malay-dev thanks for asking. Would greatly appreciate if you could contribute to this.

Please use this issue as a place for any questions or ideas before opening a PR.

**Comment by Malay-dev** [comment]
Hey @fershad, Can you review my Pull Request #230

**Comment by fershad** [comment]
Thanks for your contribution @Malay-dev
