### ISSUE TITLE
Default grid intensities not returned when only setting some segments in perVisitTrace

### ISSUE THREAD

**Issue by APJohns** [thegreenwebfoundation/co2.js#236]
**Describe the bug**
When only providing one segment to gridIntensity in perVisitTrace, the returned variables.gridIntensity only shows what was provided and no longer shows the default global intensity for the other segments.

**To Reproduce**
1. Call perVisitTrace using SWD model while only providing one or two segment grid intensities
2. Notice returned variables.gridIntensities only contains the ones you set

**Expected behavior**
Returned variables.gridIntensity should show all intensities (including defaults).

**Environment (please complete the following information):**
 - NodeJS

**Comment by fershad** [comment]
@APJohns thanks for this. I've seen your PR too. I'll have a look at these on Friday this week when I've got a bit more bandwidth.

**Comment by fershad** [comment]
Thanks for this issue, and for the associated PR @APJohns
