### ISSUE TITLE
Mock tests that make unnecessary network calls

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#50]
This repo uses Jest, for tests and like considerate developers, we'd like to have a decent test suite.

Sadly, the test suite makes a bunch of network calls that it doesn't really need to.

I spent about an hour this morning faffing with Jest, and trying to make sense of how to do mocks, and I've even implemented this on other projects, but this morning I couldn't get it together.

If we could change the API tests listed below (i.e. the slower ones that take a few hundred milliseconds) so they don't make network calls, it would really help, because now that we have a working CI setup again, we've seen a few cases of test runs failing because they're timing out when run against an external API.

You can see the tests below

```
npx jest --verbose

 PASS  src/hosting-database.test.js
  hostingDatabase
    checking a single domain with #check
      ✓ tries to use a local database if available  (4 ms)
    implicitly checking multiple domains with #check
      ✓ tries to use a local database if available (1 ms)

 PASS  src/hosting-json.test.js
  hostingJSON
    checking a single domain with #check
      ✓ against the list of domains as JSON (4 ms)
    implicitly checking multiple domains with #check
      ✓ against the list of domains as JSON (2 ms)

 PASS  src/co2.test.js
  co2
    perByte
      ✓ returns a CO2 number for data transfer using 'grey' power (4 ms)
      ✓ returns a lower CO2 number for data transfer from domains using entirely 'green' power (2 ms)
    perPage
      ✓ returns CO2 for total transfer for page (15 ms)
      ✓ returns lower CO2 for page served from green site (7 ms)
      ✓ returns a lower CO2 number where *some* domains use green power (5 ms)
    perDomain
      ✓ shows object listing Co2 for each domain (7 ms)
      ✓ shows lower Co2 for green domains (7 ms)

 PASS  src/hosting-api.test.js
  hostingAPI
    checking a single domain with #check
      ✓ using the API (178 ms)
    implicitly checking multiple domains with #check
      ✓ using the API (198 ms)

 PASS  src/hosting.test.js
  hosting
    checking all domains on a page object with #checkPage 
      ✓ it returns a list of green domains, when passed a page object (416 ms)
    checking a single domain with #check
      ✓ use the API instead (233 ms)
    implicitly checking multiple domains with #check
      ✓ Use the API (130 ms)
    explicitly checking multiple domains with #checkMulti
      ✓ use the API (149 ms)
```

And the docs for Jest mocks are below:

https://jestjs.io/docs/mock-functions#using-a-mock-function

**Comment by soulgalore** [comment]
@mrchrisadams I can have a go later this week. I would change so `hosting.test.js` test against the local database and then only mock for testing the actual API path `hosting-api.test.js`?

**Comment by mrchrisadams** [comment]
Thanks Peter, I'd really appreciate that 👍 

I think `hosting.test.js` is testing functionality that we already test in `hosting-api.test.js` anyway, so having tests that exercise the code that calls the API there too isn't actually adding much value - I think we could just test that it's calling methods on the hosting API object.

I'm happy to defer to you on this one though, as I learned a bunch of nice tricks from reading your earlier PRs, like making HTTP requests without axios/fetch etc. :D
