### ISSUE TITLE
Change master branch to main (or something else)?

### ISSUE THREAD

**Issue by soulgalore** [thegreenwebfoundation/co2.js#54]
https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by mrchrisadams** [comment]
Thanks for these steps Peter - we're now using `main` in this repo. I'll check about the the github actions too now

**Comment by mrchrisadams** [comment]
Ah, the actions were already set to check for `main`. I think that would explain why #53  hadn't triggered a build
