### ISSUE TITLE
Include model used for website carbon, ecoping, and the rest

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#56]
This model is used in a number of places:

https://sustainablewebdesign.org/calculating-digital-emissions/

There's a bit more research needed for what I was referring to as the Green Byte Model in in #2, but it would be useful to have the different models in used available, so you can choose between:

- the shift project model
- one containing the values above
- whatever model the green web foundation eventually comes up with

## Acceptance criteria

- [x] Sustainable Web Design model exists as a model along side the existing 1bytemodel
- [x] CONSTANTS and links back to the original methodology page exist where it came from
- [x] Test exist, demonstrating: 
  -  [x] instantiating the CO2 object with SWD, and querying the model to see which model is in use (i.e. is it SWD? is it the 1 byte model?)
  -  [x] exercising the CO2 code to return co2 emissions for a gigabyte of transfer, all defaults (default carbon intensity)
  -  [x] exercising the CO2 code to return co2 emissions for a gigabyte of transfer, with a 'green' domain (i.e. energy is matched from renewable sources, or comes directly from renewable sources)
  - [x] some notional error handling for when we pass in bad input (I'm not sure how much typescript might give us for free here, so there's no need to really go into too much depth)

In all cases we'd want to be able to call `perbyte` to return a single number for compatibility, and have a way to return an object with scope for more complex return info (so we can refer to specific parts of the SWD result breakdown or other info)

**Comment by drydenwilliams** [comment]
Thanks for this @mrchrisadams great detail, I will try and have a look through properly in the next week.

**Comment by mrchrisadams** [comment]
Dryden's PR for this is at the link below. 

I'll flesh out a few more acceptance criteria so it's clearer what it would make sense to include

https://github.com/thegreenwebfoundation/co2.js/pull/58

**Comment by mrchrisadams** [comment]
These are the numbers from the website carbon API, which I understand to be older than model outlined at the [digital emissions page](https://sustainablewebdesign.org/calculating-digital-emissions/). These are the key constants they've been using, which the new information supersedes.

```js
const KWG_PER_GB = 1.805;
const RETURNING_VISITOR_PERCENTAGE = 0.75;
const FIRST_TIME_VIEWING_PERCENTAGE = 0.25;
const PERCENTAGE_OF_DATA_LOADED_ON_SUBSEQUENT_LOAD = 0.02;
const CARBON_PER_KWG_GRID = 475;
const CARBON_PER_KWG_RENEWABLE = 33.4;
const PERCENTAGE_OF_ENERGY_IN_DATACENTER = 0.1008;
const PERCENTAGE_OF_ENERGY_IN_TRANSMISSION_AND_END_USER = 0.8992;
const CO2_GRAMS_TO_LITRES = 0.5562;
```

As I understand it, Websitecarbon's averages weren't based on the HTTP Archive, but on the stored values in their own dataset (I might be wrong here - it might be worth asking Tom).

### About dynamic visitor figures

> Should visitor figures be dynamic? I think it should be. Currently, they are hardcoded to:
> 
> -   `0.75` returning visitors
> -   `0.25` for new users
> -   `0.02` for subsequent data loaded

The general principle I get from reading the SWD description is along these lines:

> provide some defensible defaults in the absence of data, but support using data if it exists

Generally speaking, the approach I think we should follow is have these as constant values for now, with the option to pass overrides in if you have them.

**Comment by drydenwilliams** [comment]
Morning @mrchrisadams, I've just asked Tom about the transfer size they used so interested to hear and keep you posted. I think we should use the hardcoded ones in your example (which I've added in my PR) but not all of them are needed anymore. We should make them dynamic (we would need this on EcoPing to use this model)... but could lead to different calculations everywhere, but at least they make sense as grid intensity and caching change it, which makes sense? I propose something like: 

```
energyPerVisit(bytes, returningVisitorPct = 0.75, firstTimeVisitorPct = 0.25, subsequentLoadPct = 0.02) {
    const transferedBytesToGb = bytes / fileSize.GIGABYTE;
    return (
      transferedBytesToGb * KWH_PER_GB * returningVisitorPct +
      transferedBytesToGb *
        KWH_PER_GB *
        firstTimeVisitorPct *
        subsequentLoadPct
    );
  }

  emissionsPerVisitInGrams(energyPerVisit, globalIntensity = GLOABL_INTENSITY) {
    return formatNumber(energyPerVisit * globalIntensity);
  }
```

and adding a new helper function like Website Carbon API like: 

```
 getStatistics(
    bytes,
    globalIntensity = GLOABL_INTENSITY,
    returningVisitorPct = 0.75,
    firstTimeVisitorPct = 0.25,
    subsequentLoadPct = 0.02
  ) {
    const energy = this.energyPerVisit(
      bytes,
      returningVisitorPct,
      firstTimeVisitorPct,
      subsequentLoadPct
    );
    const co2gramsPerView = this.emissionsPerVisitInGrams(energy, globalIntensity);

    return {
      bytes
      intensity: globalIntensity,
      co2grams: co2gramsPerView,
    };
  };
```

**Comment by mrchrisadams** [comment]
@drydenwilliams can you let me know how you're handling this when a website makes requests to multiple domains in multiple places?

We originally implemented the "per byte" approach to provide a low level way to think about data transfers, and now that I've seen the examples and PR, I think the SWD model you're using is actually working at a higher level than we were.

For example, the CO2 js approach so far was designed to allow for the case of a single website visit creating connections to multiple different domains - each of which might have different CO2 intensities, as the files are being served from places on different grids, and because you can't directly control the path data takes a it routes through the network.

The _per byte_ approach was also originally designed to allow for more than just website visits (think of streaming videos, making large software downloads, peer to peer transfer and so on) - I'd really like to avoid losing this extra granularity, as it limits where you could use these models.

Previously we've avoided the issue of caching for this reason - on a website visit load, we didn't think we had enough information to make a defensible assumption about which resources are cached at the website visit level, and it would have to be addressed on a per request level instead.


### A way to support both - splitting out the two models


With this in mind, I think it might be possible to have separate out these two idea, so you might have a `perByte` method for the transfer part (containing assumptions about carbon intensity between various points), which is called by a higher level `perWebsiteVisit` method (containing the assumptions about device emissions, caching and the rest).

This approach would keep the model as being compatible (so folks who have data collected would be able to drop in the SWD model for transfer), whilst supporting the higher level "website visit" use case.

### Carbon intensity

I realise in the original issue it was probably wasn't too clear, but the intention was that the second and third arguments would be _optional_, with fallbacks to global constants in the absence of either data from the provider, or input from the consumer of the model.

I'm trying to follow this general principle here:

> provide some defensible defaults in the absence of data, but support using data if it exists


#### The second argument - green/ not green

The second boolean argument would account for the green energy case as used in website carbon, sitespeed.io, and in CO2.js right now .

You might think of this second argument as covering the case of _market based emissions reductions_ when measuring Scope 2 emissions in the GHG protocol.

At the green web fdn, we use the green / not green largely because we _do_ recognise where people are matching fossil energy use with green energy tariffs and the rest, rather than only measuring the direct emissions.

We outline a bit more [on the green web foundation website about evidence we accept and why](), as does [Microsoft, with their own reasoning about systemic change versus local change ](https://devblogs.microsoft.com/sustainable-software/do-you-want-to-be-powered-by-renewables-the-answer-is-no/). 

However, I know that [Ecoping doesn't recognise these reductions](https://ecoping.earth/faqs), nor does the [software carbon intensity spec](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/main/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#location-based-marginal-carbon-intensity-i). Even with the GHG protocol, this is somewhat recognised by the existence of the _location based_ emissions in Scope 2 too.

I really think having having this as separate from from the time and location based info is important for clarity, but capturing this is important. Going from a boolean to something richer (like percentage of the year matched with carbon free power) might make sense in future, but for now, a boolean is API compatible and easy to implement.

This whole topic is a massive rabbithole, this piece is probably the best summary of the different points of view. 

https://www.volts.wtf/p/is-247-carbon-free-energy-the-right

#### The third argument - temporal and geographic carbon intensity 

The third argument here was to support this geographical and temporal resolution information you refer to, that Ecoping uses, but as I understand it, Ecograder and Website Carbon do not. There is this issue in WebPageTest to start incorporating these figures too, but but discussions about carbon intensity data haven't come up yet:

https://github.com/WPO-Foundation/webpagetest/issues/1613

Anyway - access to this data in isn't universal and free yet, and depending on the use cases, the extra detail might not always be worth the extra effort and cost. There's a project I'm working on to get some of this data released as open data](https://github.com/Green-Software-Foundation/sci-data), but the timeframe goes beyond the scope of this issue.

In this case here, as long as you're providing the same input data, and have a clearly understood way for going from a website visit to carbon emissions in the model, I think it's okay to have different providers implement different levels of detail carbon intensity wise.

This was the thinking for this part here in the issue:

```js

const timeAndSpace = { 
	deviceCountry: "AUS-QLD", deviceTimestamp: "2021-12-13T16:40:27.614Z",
	serverCountry: "FR"
}


const co2Amount = co2Converter.perByte(
	GIGABYTE, 
	GREEN, 
	timeAndSpace
)
```

Even if software implementing this model doesn't use higher resolution data yet, supporting higher resolution input as an optional argument would be worthwhile in the model .

#### An update path and data portability

Over time, I think more data about carbon intensity of electricity will likely become more freely available, but having something like EcoPing available now provides an API compatible upgrade path for folks who need get higher resolution carbon emissions info if needed, even if they have started out with other tooling.

This is an open project, and if we want to support upgrade paths like this, it would make sense to know there are entirely OSS options exist too - in fact some orgs won't use proprietary tools unless there is OSS alternative they can migrate back out to.

If they needed to folks who need an OSS option could [still deploy the sitespeed suite](https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/), and [deploy many of the same scrapers that Electricity Map uses](https://github.com/electricityMap/electricitymap-contrib) - this is what I understand Ecoping does.


## Summary: separate perbyte and pervisit methods, overrideable defaults, and the three arguments for perbyte

@drydenwilliams can you would you please implement the `perByte` method in the system as the lower level part of the model for transfer? I'm open to discussing alternatives as long as the meet the criteria above, and the requirements for API compatibility, to support switching from one model to another one given something like a harfile or other structured representation of a webpage visit.

**Comment by mrchrisadams** [comment]
I'm closing this, as we now have the SWD implemented largely with tests as outlined in the issues #67 and #58.
