### ISSUE TITLE
Add country level data from Ember to replace IEA figures

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#64]
Ember's global electricity report 2022 was released today.

https://ember-climate.org/insights/research/global-electricity-review-2022/

This has openly licensed country-level data on power generation and carbon intensity of electricity, from 2021 all the way back to 2000, that is nice and easy to download, and explore here:

https://ember-climate.org/data/data-explorer/

The data is licensed CC-BY-SA 4.0:
https://ember-climate.org/creative-commons/

This means we can freely include it to make local lookups possible - probably starting with the latest year for each country.

**Comment by mrchrisadams** [comment]
I've made some progress with #69 here.

We don't have these added as constants yet though, but I'm not sure if we'd need them.

**Comment by fershad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Include EMBER and UNFCCC data in CO2.js](https://trello.com/c/vcBJO5ig/69-include-ember-and-unfccc-data-in-co2js)

**Comment by fershad** [comment]
#69 has been merged which adds this data to the library. Next steps will be:

- Provide and easy way to import the data for use
- Provide an API to make using the data _even_ easier

**Comment by fershad** [comment]
Okay to close this @mrchrisadams ? The import & API items mentioned above can be tracked in separate issues (import is already in #106)

**Comment by mrchrisadams** [comment]
Hi @fershad , yeah, this is good to close.

I'll close it, and add a few notes to #106
