### ISSUE TITLE
Error running example code [TypeError: CO2 is not a constructor]

### ISSUE THREAD

**Issue by wisefool** [thegreenwebfoundation/co2.js#70]
Hello,

I'm attempting to run co2.js as a server-side module and cannot get the example code to run.

I'm using the example verbatim:

```
const CO2 = require('@tgwf/co2')
const bytesSent = (1024 * 1024 * 1024)
const co2Emission = new CO2();
estimatedCO2 = co2Emission.perByte(bytesSent)`

console.log(`Sending a gigabyte, had a carbon footprint of ${estimatedCO2.toFixed(3)} grams of CO2`)
```

However the line `const co2Emission = new CO2();` gives the following error when I attempt to run:

```const co2Emission = new CO2();
                                        ^
TypeError: CO2 is not a constructor
    at Object.<anonymous> (/var/www/ecograder/co2/api/index.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
 ```
 
 Also attempted to test on npm.runkit.com and it gives the same error:
 
<img width="662" alt="runkit_error" src="https://user-images.githubusercontent.com/1641734/162268175-1d5897cb-c9cd-4358-89de-5f859b6e7190.png">

Looking at the src it appears CO2 is exported properly.

**Comment by mrchrisadams** [comment]
hi @wisefool  - sorry about that! I see the error here now.

This here shows a test demonstrating how it's intended to work:

https://github.com/thegreenwebfoundation/co2.js/blob/v0.8.0/src/co2.test.js

And for the SWD module in the new release, 0.9 these tests should show some expected use:

https://github.com/thegreenwebfoundation/co2.js/blob/v0.9.0-0/src/sustainable-web-design.test.js
https://github.com/thegreenwebfoundation/co2.js/blob/v0.9.0-0/src/co2.test.js

For the node code example in the readme though, I realise the entry point with `var co2 = require("@tgwf/co2")` is importing the _co2js module, not the CO2 class inside the CO2 module_ 😱 

This would explain the error. for 0.8, on nodejs, you'd need to refer to the _class_, not the module. 

```js

// import the module
var co2module = require("@tgwf/co2")

// make an instance of the class for converting the transfer to emissions
// this defaults to the 1byte model in use already, for backwards compatibility.
const convertedToEmissions = new co2module.co2()

// convert the data transfer, assuming you care about transfer
const amount = convertedToEmissions.perByte(1000 * 1000 * 1000)

console.log(amount)  // should be around 290 grams
```

![Screenshot 2022-04-08 at 09 45 13](https://user-images.githubusercontent.com/17906/162390744-5a93f527-b76d-4c85-ac70-ac4e76f26788.png)

### A sensible fix for this

I'll update the readme, but in the long run, having a simple default import with the class already instantiated would be nice, as @drydenwilliams suggested in some feedback when trying out the pre-release this week.

Would something like this work for you?

```js

// import pre-instantiated model for doing conversions, using the SWD model
import { swd } from '@tgwf/co2'

// convert the data for transfer if the assumptions about caching don't fit your use case
const estimateWithNoCaching = swd.perByte(1000 * 1000 * 3)

// convert the data for a website visit
const estimateWithCaching = swd.emissionsPerVisitInGrams(1000 * 1000 * 3)

console.log(estimateWithNoCaching) 
```

**Comment by wisefool** [comment]
Hey, that's great. Thank you. I thought I had tried CO2.co2() but perhaps I had the capitalization wrong.

Everything works as expected now.
