### ISSUE TITLE
Remove database name from package and use the full path

### ISSUE THREAD

**Issue by soulgalore** [thegreenwebfoundation/co2.js#8]
Hi @mrchrisadams so about keeping the actual file name in the package.json file: The idea of that was to keep the actual database in the same module. Then for example when you published a new version of it, you only need to change the name and the publish the package. 

As a user of the API, I think its cleaner if I would give the full path and name to my local database, that way I think cleaner to understand where to put it. If I include co2.js in another module, at the moment co2.js will look at the package.json for c02, not the one for the package that includes it.

So if you feel ok with it, I want to do a PR that:
* remove the names database from the package.json
* take the full path and the name database

Also if its ok for you I wanna split the code so we have internally to different JS files, one for calling the API and for calling the database. We can have the same interface but I kind of like splitting the code into multiple files so its a little easier to read?

And last thing for now: How do you feel about the method signatures? Do you always want to feed the API with path to the database for each method or do you initialise and object that holds all the info?

And final finally, I'm curious about finding another sqlite database lib, since we only need to so simple things. I will have a look if I find something else, and if I do, I'll create an issue.

**Comment by mrchrisadams** [comment]
TBH, I've just been thinking about two separate versions too, as I wasn't all that happy with the single module doing both like we have it.

I went a bit down a rabbithole looking at lerna and stuff to see how best we could do that, but I totally support this.

**Comment by mrchrisadams** [comment]
So, we're thinking something like this right?

- `hosting.js` - just the API
- `hosting-db.js` - uses a local database

Right? I suspect the API is likely to be used more, and will have the more update info, so it would be good to force an API call from the db module in some cases, but, it's not a thing I'm religious about.

**Comment by soulgalore** [comment]
Yes exactly. I updated the PR and it passes, so please have look when you have time. If it passes your eyes it would be great if you could push a new version to npm, then I can update the PR in sitespeed.io by inlcuding the latest version of the database and we are ready to merge :)

**Comment by soulgalore** [comment]
Done
